### ISSUE TITLE
Api call failed

### ISSUE THREAD

**Issue by Eamon-0v0** [anythingworld/anything-world-python#2]
Hello, my api calls are based on this library.
Unfortunately, I only success to run the provided demo example, and the api doesn't work successfully for my own files. The code is：

```
 response = client.animate(
        files_dir='./a_cute_bear_in_a_pair_of_romper0.glb',
        model_name='a cute bear',
        model_type='a cute bear',
        auto_rotate=True,
        is_symmetric=True
    )

```
The **glb** file is here:
[a cute bear in a pair of romper0.zip](https://github.com/user-attachments/files/17829131/a.cute.bear.in.a.pair.of.romper0.zip)

When running it, I get the following error:

```
Exception: Generic API error: RiggingError: RiggingError: 673da96adcdf69349cd9a1ae (model ID: Classification category biped_small__walk is not supported at the moment.)
MissingData: MissingData: Failed to retrieve partitioning output of rigging skeleton. (model ID: 673da96adcdf69349cd9a1ae)
DatabaseError: Error: No information available for models to upload
FileError: FileError: File /app/UNSEGMENTED/673da96adcdf69349cd9a1ae__1732094359_9923644/a_cute_bear_in_a_pair_of_romper0.fbx is missing. (model ID: 673da96adcdf69349cd9a1ae)
FileError: FileError: File /app/UNSEGMENTED/673da96adcdf69349cd9a1ae__1732094359_9923644/a_cute_bear_in_a_pair_of_romper0_rig_info.txt is missing. (model ID: 673da96adcdf69349cd9a1ae).
```
But generate from the web page using the same parameters can get the correct generated result.

Can you please help me to see why this is happening?

All the best！！！

**Comment by automata** [comment]
Hello @Eamon-0v0! We checked the error for your specific model, and unfortunately we don't support the `small humanoids` category yet.

However, you should be able to rig and animate other models. We just released a [new version](https://pypi.org/project/anything-world/0.2.0) of the package (`0.2.0`) with a few fixes and with new support to generate 3D models from text prompt or image, so it would suggest you to update the package and try again with other models.

Closing this issue for now, please feel free to re-open it if necessary. Thank you!
